-- ═══════════════════════════════════════════════════════════════════
-- MOVED — the migration ledger now lives in supabase/migrations/
--
-- This single rolling file was retired on 2026-07-25 after it silently
-- dropped a version (v85) during a rewrite and production drifted three
-- versions behind. The replacement is one numbered, APPEND-ONLY file per
-- schema version:
--
--   supabase/migrations/0085_billing_and_export_grants.sql
--   supabase/migrations/0086_student_verification.sql
--   supabase/migrations/0087_scheduled_pack_release.sql
--   supabase/migrations/0088_mailing_list.sql
--   supabase/migrations/0089_community_foundations.sql
--   supabase/migrations/0090_admin_audit.sql      ← outstanding, run me
--
-- Workflow: open supabase/migrations/README.md, check the status table,
-- paste each outstanding file into the Supabase SQL editor in filename
-- order (each is idempotent — re-running is harmless), then tick it off
-- in the README. Never edit an applied file; new work gets a new number.
-- ═══════════════════════════════════════════════════════════════════
