/* ── The background library catalog ──────────────────────────────────
   GENERATED from the owner's 82-image "Game Background Library" drop
   (bg-drop-1) — regenerate via the catalog JSON archived in
   docs/background-library/, do not hand-edit entries.

   Thumbs ship with the app (public/bg-thumbs/<id>.webp, ~10KB each);
   full-res WebPs live in the Supabase "backgrounds" storage bucket and
   are addressed from the same Supabase project the app already runs on
   — boards store that URL, never pixels. */

import { cloudConfig } from "./cloud";

export type BackdropEntry = {
  id: string;      // file slug — thumb name and bucket object name
  title: string;
  cat: string;     // genre folder from the drop
  land: boolean;   // landscape 1920×1080; false = portrait 1080×1920
  dot: string;     // dominant color, for the picker's color dot
  hay: string;     // search haystack: title + genre + tags + palette
};

export const BACKDROP_CATEGORIES: string[] = ["Adventure & Platformer","Characters & Lifestyle","City & Traffic","Cooking & Food","Fantasy & Medieval","Kids & Casual","Nature & Scenic","Simulation & Lifestyle","Strategy & Battle"];

export function backdropThumb(id: string): string {
  return `/bg-thumbs/${id}.webp`;
}

/** Full-res bucket URL — null while the app has no Supabase config
    (local-only builds), which also hides the picker. */
export function backdropUrl(id: string): string | null {
  const cfg = cloudConfig();
  return cfg ? `${cfg.url}/storage/v1/object/public/backgrounds/${id}.webp` : null;
}

export const BACKDROP_LIBRARY: BackdropEntry[] = [
  { id: "frostwhistle-summit", title: "Frostwhistle Summit", cat: "Nature & Scenic", land: true, dot: "#6CA6DB", hay: "frostwhistle summit nature & scenic adventure role-playing game exploration puzzle snowy mountain pine forest daylight winter wilderness serene uplifting crisp stylized illustration painterly casual game art cyan cyan turquoise white" },
  { id: "moonriver-pines", title: "Moonriver Pines", cat: "Nature & Scenic", land: true, dot: "#063568", hay: "moonriver pines nature & scenic adventure role-playing game survival exploration moonlit mountain valley winding river pine forest night mysterious calm atmospheric stylized landscape painterly fantasy environment turquoise turquoise blue" },
  { id: "cloudcrown-peak", title: "Cloudcrown Peak", cat: "Nature & Scenic", land: true, dot: "#49A6D7", hay: "cloudcrown peak nature & scenic adventure role-playing game exploration puzzle snowy mountain pine forest clouds daylight heroic serene bright stylized illustration painterly casual game art turquoise turquoise cyan white" },
  { id: "midnight-meeple-club", title: "Midnight Meeple Club", cat: "Simulation & Lifestyle", land: true, dot: "#17241A", hay: "midnight meeple club simulation & lifestyle social simulation board game visual novel narrative adventure cozy game room tabletop game anthropomorphic friends interior cozy mischievous social anime-inspired cartoon illustration character scene green green orange olive silver" },
  { id: "toolbelt-tuesday", title: "Toolbelt Tuesday", cat: "Characters & Lifestyle", land: false, dot: "#5E85A3", hay: "toolbelt tuesday characters & lifestyle repair simulation time management character customization casual workshop interior utility room handyman tiled floor cheerful industrious friendly stylized three-dimensional cartoon character casual game art turquoise turquoise sky blue violet" },
  { id: "mango-monkey-hop", title: "Mango Monkey Hop", cat: "Adventure & Platformer", land: false, dot: "#79591E", hay: "mango monkey hop adventure & platformer endless jumper platformer casual arcade kids game tropical jungle floating blocks coins monkey playful energetic sunny stylized three-dimensional cartoon mobile game art brown brown teal green" },
  { id: "strawberry-skyfall", title: "Strawberry Skyfall", cat: "Adventure & Platformer", land: false, dot: "#7FCBAC", hay: "strawberry skyfall adventure & platformer fruit catcher casual arcade match and merge kids game desert canyon giant strawberry floating fruit open sky whimsical juicy bright stylized three-dimensional cartoon mobile game art green green orange yellow gold" },
  { id: "ember-isle", title: "Ember Isle", cat: "Adventure & Platformer", land: true, dot: "#822D2F", hay: "ember isle adventure & platformer adventure exploration strategy narrative game island city ocean sunset fortress cinematic mysterious warm stylized three-dimensional painterly environment concept art red red magenta crimson" },
  { id: "coral-concrete-run", title: "Coral Concrete Run", cat: "Adventure & Platformer", land: true, dot: "#5D8EAF", hay: "coral concrete run adventure & platformer action platformer parkour adventure precision platformer brutalist ruins red concrete open sky parkour course energetic daring sunlit stylized three-dimensional painterly action game art turquoise turquoise red cyan blue" },
  { id: "crimson-cat-caper", title: "Crimson Cat Caper", cat: "Adventure & Platformer", land: true, dot: "#5E331C", hay: "crimson cat caper adventure & platformer platformer cooperative game puzzle platformer action adventure red stone ruins crates cats side-scrolling level playful adventurous colorful hand-painted two-dimensional cartoon side-scroller orange orange teal green" },
  { id: "night-owl-uprising", title: "Night Owl Uprising", cat: "Adventure & Platformer", land: true, dot: "#334924", hay: "night owl uprising adventure & platformer platformer action adventure creature battler side-scroller industrial city dark owl monsters wooden platforms colorful skyline chaotic spooky vibrant hand-painted two-dimensional cartoon side-scroller green green turquoise teal red" },
  { id: "emerald-deerway", title: "Emerald Deerway", cat: "Nature & Scenic", land: true, dot: "#8BA756", hay: "emerald deerway nature & scenic exploration adventure cozy role-playing game walking simulator forest road deer green valley woodland peaceful pastoral inviting painterly stylized landscape cozy game art lime lime green olive" },
  { id: "little-shadow-sunrise", title: "Little Shadow Sunrise", cat: "Adventure & Platformer", land: true, dot: "#80B0BC", hay: "little shadow sunrise adventure & platformer adventure platformer narrative game minimalist puzzle exploration pastel mountains red sun grassland silhouettes quiet poetic contemplative minimalist two-dimensional silhouette graphic illustration teal teal olive orange silver" },
  { id: "paintstorm-parade", title: "Paintstorm Parade", cat: "Adventure & Platformer", land: true, dot: "#688478", hay: "paintstorm parade adventure & platformer action shooter arena battler first-person shooter party game abstract arena paint splashes water futuristic structures explosive vibrant surreal stylized three-dimensional graphic high-energy action art green green red gold" },
  { id: "scarlet-blockdream", title: "Scarlet Blockdream", cat: "Adventure & Platformer", land: true, dot: "#5C9BAD", hay: "scarlet blockdream adventure & platformer puzzle platformer narrative adventure exploration art game abstract block city red monoliths lone figure open sky dreamlike lonely bold minimalist three-dimensional graphic surreal environment teal teal orange rose silver" },
  { id: "edge-of-ember", title: "Edge of Ember", cat: "Adventure & Platformer", land: true, dot: "#F25449", hay: "edge of ember adventure & platformer precision platformer puzzle silhouette adventure indie platformer cliff edge red sunset dark platforms mountains tense minimal cinematic silhouette two-dimensional minimalist graphic rose rose yellow orange" },
  { id: "graffiti-gravity", title: "Graffiti Gravity", cat: "Adventure & Platformer", land: true, dot: "#C93F43", hay: "graffiti gravity adventure & platformer skateboarding parkour action sports open-world adventure urban alley graffiti skate park city ruins rebellious energetic streetwise stylized three-dimensional comic-inspired urban game art red red gray teal orange gold" },
  { id: "peachblock-passage", title: "Peachblock Passage", cat: "Adventure & Platformer", land: true, dot: "#841C1C", hay: "peachblock passage adventure & platformer puzzle platformer casual minimalist adventure indie game pink block world blue character platforms sunset warm quirky minimal stylized two-dimensional pixel-inspired graphic red red rose orange" },
  { id: "sunset-signal", title: "Sunset Signal", cat: "Adventure & Platformer", land: true, dot: "#533112", hay: "sunset signal adventure & platformer narrative adventure exploration cozy game walking simulator sunset pier harbor industrial shoreline lone character reflective warm cinematic stylized three-dimensional painterly narrative game art brown brown olive orange" },
  { id: "grumble-giants", title: "Grumble Giants", cat: "Adventure & Platformer", land: true, dot: "#DE7063", hay: "grumble giants adventure & platformer puzzle platformer casual arcade kids game indie platformer red block ruins giant stone faces mountains side-scrolling level whimsical curious warm pixel-inspired two-dimensional cartoon side-scroller rose rose red peach gold" },
  { id: "neon-snowbound", title: "Neon Snowbound", cat: "Adventure & Platformer", land: true, dot: "#0F262D", hay: "neon snowbound adventure & platformer action adventure role-playing game exploration cyberpunk snowy neon village night street colorful buildings lone character nocturnal electric mysterious stylized three-dimensional painterly neon environment art teal teal magenta turquoise blue" },
  { id: "magenta-moonrise", title: "Magenta Moonrise", cat: "Adventure & Platformer", land: true, dot: "#812A37", hay: "magenta moonrise adventure & platformer cyberpunk role-playing game narrative adventure exploration visual novel neon city giant pink moon pagoda rooftops night moody cinematic futuristic stylized three-dimensional painterly neon cityscape red red magenta crimson" },
  { id: "last-watchtower", title: "Last Watchtower", cat: "Adventure & Platformer", land: true, dot: "#53413C", hay: "last watchtower adventure & platformer survival exploration narrative adventure strategy abandoned tower rural industrial site pink sky wasteland lonely atmospheric windswept stylized three-dimensional painterly environment concept art orange orange periwinkle rose turquoise" },
  { id: "brickwater-bounce", title: "Brickwater Bounce", cat: "Adventure & Platformer", land: false, dot: "#C73920", hay: "brickwater bounce adventure & platformer vertical platformer mobile arcade puzzle kids game pixel water shaft brick platforms cute blocks vertical level playful retro bright pixel art two-dimensional mobile game art red red teal orange olive green" },
  { id: "taxi-tangle", title: "Taxi Tangle", cat: "City & Traffic", land: false, dot: "#7E3C41", hay: "taxi tangle city & traffic traffic puzzle city simulation taxi game management isometric city roads cars downtown busy playful colorful low-poly isometric stylized three-dimensional mobile game art red red turquoise gray orange teal" },
  { id: "candy-city-rush", title: "Candy City Rush", cat: "City & Traffic", land: false, dot: "#EA5071", hay: "candy city rush city & traffic endless driver traffic racer city simulation casual arcade bright city canyon cars downtown street vertical road energetic sunny fast low-poly isometric stylized three-dimensional mobile game art rose rose orange turquoise red silver" },
  { id: "crosswalk-commotion", title: "Crosswalk Commotion", cat: "City & Traffic", land: false, dot: "#836D5A", hay: "crosswalk commotion city & traffic traffic management puzzle simulation mobile game isometric roads vehicles pedestrians city blocks busy strategic playful low-poly isometric stylized three-dimensional mobile game art orange orange gold" },
  { id: "pizza-palace", title: "Pizza Palace", cat: "Cooking & Food", land: true, dot: "#4B3130", hay: "pizza palace cooking & food cooking game restaurant simulation time management tycoon pizzeria kitchen pizza ingredients restaurant interior inviting cheerful abundant stylized three-dimensional cartoon casual game art red red orange gold" },
  { id: "plushie-patisserie", title: "Plushie Patisserie", cat: "Cooking & Food", land: true, dot: "#A6684D", hay: "plushie patisserie cooking & food cooking game bakery simulation time management kids game whimsical bakery plush animals pastries restaurant interior cute cozy playful stylized three-dimensional cartoon casual game art orange orange red gold" },
  { id: "monster-microwave", title: "Monster Microwave", cat: "Cooking & Food", land: true, dot: "#B61A28", hay: "monster microwave cooking & food cooking game arcade restaurant simulation boss battle monster kitchen ovens neon appliances fantasy restaurant mischievous intense quirky cartoon two-dimensional graphic monster game art red red crimson blue turquoise" },
  { id: "sizzle-circle", title: "Sizzle Circle", cat: "Cooking & Food", land: true, dot: "#BF341B", hay: "sizzle circle cooking & food cooking game cooperative game restaurant simulation party game commercial kitchen chefs pizza restaurant energetic communal warm stylized illustration cartoon character scene red red orange gold" },
  { id: "sunshine-pizzeria", title: "Sunshine Pizzeria", cat: "Cooking & Food", land: true, dot: "#37372A", hay: "sunshine pizzeria cooking & food cooking game restaurant simulation time management casual modern pizzeria pizza vegetables sunny kitchen fresh cheerful polished stylized three-dimensional cartoon casual game art yellow yellow red orange gold" },
  { id: "tiny-chefs-club", title: "Tiny Chefs Club", cat: "Cooking & Food", land: true, dot: "#E45837", hay: "tiny chefs club cooking & food cooking game kids game educational game time management home kitchen children cooking ingredients colorful interior friendly playful educational flat cartoon two-dimensional children illustration casual game art red red teal green" },
  { id: "harborhold-kingdom", title: "Harborhold Kingdom", cat: "Fantasy & Medieval", land: false, dot: "#34413A", hay: "harborhold kingdom fantasy & medieval kingdom builder city builder strategy role-playing game coastal medieval town harbor ship red rooftops bustling adventurous inviting isometric two-dimensional stylized map fantasy game art green green red teal" },
  { id: "greenfield-procession", title: "Greenfield Procession", cat: "Fantasy & Medieval", land: false, dot: "#817B51", hay: "greenfield procession fantasy & medieval kingdom builder tactics city builder role-playing game medieval village crowds fields roads lively pastoral strategic isometric stylized map illustration fantasy game art yellow yellow green orange" },
  { id: "castlewood-crown", title: "Castlewood Crown", cat: "Fantasy & Medieval", land: false, dot: "#154043", hay: "castlewood crown fantasy & medieval kingdom builder city builder strategy role-playing game castle valley red roofs forest mountains grand verdant inviting isometric painterly stylized map fantasy game art teal teal lime orange" },
  { id: "siegewater-isle", title: "Siegewater Isle", cat: "Fantasy & Medieval", land: false, dot: "#47402F", hay: "siegewater isle fantasy & medieval strategy tower defense kingdom builder tactics fortified island villagers cliffs water busy tactical colorful isometric stylized strategy map fantasy game art brown brown lime orange green" },
  { id: "teal-banner-keep", title: "Teal Banner Keep", cat: "Fantasy & Medieval", land: true, dot: "#1A4534", hay: "teal banner keep fantasy & medieval role-playing game kingdom builder strategy adventure castle village banners villagers farmland heroic rustic sunlit graphic painterly stylized two-dimensional fantasy environment green green olive teal brown" },
  { id: "crimson-citadel", title: "Crimson Citadel", cat: "Fantasy & Medieval", land: true, dot: "#672D38", hay: "crimson citadel fantasy & medieval role-playing game strategy dark fantasy tower defense castle silhouettes red sunset fortress skyline wasteland ominous epic dramatic silhouette painterly dark fantasy art two-dimensional red red" },
  { id: "twin-moon-pagoda", title: "Twin Moon Pagoda", cat: "Fantasy & Medieval", land: true, dot: "#121F1C", hay: "twin moon pagoda fantasy & medieval dark fantasy role-playing game strategy adventure visual novel gothic pagoda castle twin moons birds coastal fortress mysterious majestic otherworldly painterly stylized two-dimensional dark fantasy art teal teal turquoise crimson red green" },
  { id: "furnace-fortress", title: "Furnace Fortress", cat: "Fantasy & Medieval", land: true, dot: "#435E66", hay: "furnace fortress fantasy & medieval dark fantasy role-playing game strategy platformer adventure fortress silhouettes fiery horizon watchtowers dark landscape foreboding epic intense painterly silhouette stylized two-dimensional dark fantasy art teal teal red crimson" },
  { id: "cloudvale-kingdom", title: "Cloudvale Kingdom", cat: "Fantasy & Medieval", land: true, dot: "#184646", hay: "cloudvale kingdom fantasy & medieval role-playing game city builder strategy adventure aerial mountain village lush hills red roofs castle enchanted grand peaceful painterly three-dimensional fantasy environment aerial vista teal teal turquoise silver" },
  { id: "sandstone-stronghold", title: "Sandstone Stronghold", cat: "Fantasy & Medieval", land: true, dot: "#6A5430", hay: "sandstone stronghold fantasy & medieval strategy role-playing game city builder survival desert fortress sunset sandstone walls market structures imposing austere warm stylized three-dimensional painterly fantasy environment brown brown yellow gold orange" },
  { id: "pale-banner-bastion", title: "Pale Banner Bastion", cat: "Fantasy & Medieval", land: true, dot: "#2A3829", hay: "pale banner bastion fantasy & medieval strategy role-playing game platformer adventure pale fortress bridge cliffs banners stark windswept heroic graphic two-dimensional stylized fantasy art minimal palette green green" },
  { id: "ember-cathedral", title: "Ember Cathedral", cat: "Fantasy & Medieval", land: true, dot: "#4D1E23", hay: "ember cathedral fantasy & medieval dark fantasy role-playing game strategy adventure horror gothic cathedral city fire hooded figures night ominous dramatic nocturnal painterly dark fantasy art cinematic environment red red" },
  { id: "paws-and-paperwork", title: "Paws and Paperwork", cat: "Simulation & Lifestyle", land: true, dot: "#723825", hay: "paws and paperwork simulation & lifestyle pet care management simulation office simulation casual pet shop office animals desks colorful interior playful bustling cozy low-poly three-dimensional cartoon simulation game art orange orange red yellow" },
  { id: "palmside-pitstop", title: "Palmside Pitstop", cat: "Simulation & Lifestyle", land: true, dot: "#51B7C0", hay: "palmside pitstop simulation & lifestyle driving racing open-world adventure life simulation retro roadside motel convertible car palm trees sunny street sunny nostalgic relaxed low-poly three-dimensional retro stylized open-world game art teal teal orange green lime" },
  { id: "carnival-catwalk", title: "Carnival Catwalk", cat: "Simulation & Lifestyle", land: true, dot: "#D24E4C", hay: "carnival catwalk simulation & lifestyle party game minigame collection casual sports kids game carnival water park cats inflatables rides exuberant silly bright stylized three-dimensional cartoon party game art red red turquoise gold teal" },
  { id: "poolside-royalty", title: "Poolside Royalty", cat: "Simulation & Lifestyle", land: true, dot: "#4ABEC5", hay: "poolside royalty simulation & lifestyle party game casual sports racing minigame collection water park inner tubes animals pink pool playful summery vivid stylized three-dimensional cartoon party game art teal teal rose turquoise green sky blue" },
  { id: "ooze-orbit-outpost", title: "Ooze Orbit Outpost", cat: "Strategy & Battle", land: true, dot: "#629F9D", hay: "ooze orbit outpost strategy & battle tower defense real-time strategy tactics science fiction alien island map defense towers orange slime industrial base strategic quirky high-energy hand-drawn two-dimensional cartoon strategy art map view teal teal orange yellow" },
  { id: "slimebeach-siege", title: "Slimebeach Siege", cat: "Strategy & Battle", land: true, dot: "#7AC3A4", hay: "slimebeach siege strategy & battle tower defense real-time strategy tactics casual strategy beach battlefield teal monster red base coastline playful chaotic colorful hand-drawn two-dimensional cartoon strategy art map view green green red gold yellow" },
  { id: "cannon-cove", title: "Cannon Cove", cat: "Strategy & Battle", land: true, dot: "#5EC0A9", hay: "cannon cove strategy & battle tower defense real-time strategy tactics casual strategy tropical island tank fortress coastline tactical bright action-packed hand-drawn two-dimensional cartoon strategy art map view teal teal orange gold" },
  { id: "autumnhorn-village", title: "Autumnhorn Village", cat: "Strategy & Battle", land: true, dot: "#E38F3C", hay: "autumnhorn village strategy & battle tower defense strategy role-playing game tactics autumn village map horned hall streams forest cozy strategic fantastical painterly two-dimensional fantasy strategy art map view gold gold red orange green" },
  { id: "neon-convoy", title: "Neon Convoy", cat: "Strategy & Battle", land: false, dot: "#463E33", hay: "neon convoy strategy & battle vehicle combat shoot-em-up endless shooter arcade neon city street armored convoy explosions traffic frantic explosive futuristic top-down three-dimensional arcade action art neon brown brown red silver" },
  { id: "redline-rebellion", title: "Redline Rebellion", cat: "Strategy & Battle", land: true, dot: "#BC2A1A", hay: "redline rebellion strategy & battle strategy action game shooter tower defense red battlefield robots burning structures war zone intense apocalyptic bold graphic three-dimensional stylized combat art science fiction red red rose orange turquoise gold" },
  { id: "monsterfire-melee", title: "Monsterfire Melee", cat: "Strategy & Battle", land: true, dot: "#3E343A", hay: "monsterfire melee strategy & battle tower defense tactics action role-playing game strategy fantasy battlefield giant monsters magic beams village chaotic colorful epic hand-drawn two-dimensional cartoon fantasy art battle scene magenta magenta red orange yellow" },
  { id: "pink-sky-juggernaut", title: "Pink Sky Juggernaut", cat: "Strategy & Battle", land: true, dot: "#EA7177", hay: "pink sky juggernaut strategy & battle tank combat strategy action game side-scrolling shooter giant tank fortress pink clouds industrial outpost desert absurd imposing cinematic painterly two-dimensional stylized military art side view rose rose crimson red magenta" },
  { id: "dustbowl-detonation", title: "Dustbowl Detonation", cat: "Strategy & Battle", land: true, dot: "#A94A34", hay: "dustbowl detonation strategy & battle tactics strategy vehicle combat tower defense desert battlefield tanks explosions ruined village intense dusty chaotic isometric three-dimensional stylized combat art strategy map red red orange" },
  { id: "tropic-tankstorm", title: "Tropic Tankstorm", cat: "Strategy & Battle", land: true, dot: "#EDAB6E", hay: "tropic tankstorm strategy & battle tactics strategy vehicle combat tower defense tropical town battlefield tanks fire coastline action-packed gritty sunny isometric three-dimensional stylized combat art strategy map gold gold red charcoal orange" },
  { id: "bubblegum-boulevard", title: "Bubblegum Boulevard", cat: "Kids & Casual", land: true, dot: "#4AB2DB", hay: "bubblegum boulevard kids & casual platformer casual arcade kids game adventure pastel city park clouds platforms side-scrolling level cheerful sweet breezy cartoon two-dimensional colorful platformer art side-scroller turquoise turquoise red teal" },
  { id: "whimsywood-wanderer", title: "Whimsywood Wanderer", cat: "Kids & Casual", land: true, dot: "#385A3B", hay: "whimsywood wanderer kids & casual platformer kids game adventure puzzle painterly forest blue creature whimsical trees woodland gentle magical curious storybook two-dimensional painterly children game art green green magenta teal silver" },
  { id: "jellybean-junction", title: "Jellybean Junction", cat: "Kids & Casual", land: true, dot: "#54AAC6", hay: "jellybean junction kids & casual platformer kids game casual adventure puzzle colorful houses floating platforms city skyline rooftops cheerful bouncy bright cartoon two-dimensional colorful platformer art side-scroller teal teal red green" },
  { id: "cloudblob-cliffs", title: "Cloudblob Cliffs", cat: "Kids & Casual", land: true, dot: "#56BDD4", hay: "cloudblob cliffs kids & casual platformer kids game casual adventure puzzle mountain cliffs blob creatures floating islands clouds adventurous airy playful cartoon two-dimensional colorful platformer art side-scroller teal teal green" },
  { id: "bath-time-brightside", title: "Bath Time Brightside", cat: "Simulation & Lifestyle", land: true, dot: "#4CB3BB", hay: "bath time brightside simulation & lifestyle life simulation dress-up game home decoration kids game colorful bathroom laundry room child toys cheerful cozy polished stylized three-dimensional cartoon character casual game art teal teal gold red green" },
  { id: "pumpkin-cat-forest", title: "Pumpkin Cat Forest", cat: "Kids & Casual", land: true, dot: "#642D5E", hay: "pumpkin cat forest kids & casual platformer kids game adventure puzzle orange monster forest cats platforms spooky trees spooky-cute playful energetic cartoon two-dimensional colorful platformer art side-scroller violet violet peach crimson orange gold" },
  { id: "sunnycat-sprint", title: "Sunnycat Sprint", cat: "Kids & Casual", land: true, dot: "#617D20", hay: "sunnycat sprint kids & casual platformer kids game endless runner casual arcade sunny forest red cat floating blocks grassland bright friendly upbeat cartoon two-dimensional colorful platformer art side-scroller olive olive teal orange lime" },
  { id: "mushroom-moonhop", title: "Mushroom Moonhop", cat: "Kids & Casual", land: true, dot: "#324120", hay: "mushroom moonhop kids & casual platformer kids game adventure puzzle colorful mushroom forest flying cats platforms flowering trees whimsical dreamy vibrant cartoon two-dimensional colorful platformer art side-scroller olive olive teal red orange green" },
  { id: "sharkberry-reef", title: "Sharkberry Reef", cat: "Kids & Casual", land: false, dot: "#14B3D4", hay: "sharkberry reef kids & casual underwater adventure match-three kids game casual arcade coral reef shark tropical fish bubbles playful aquatic bright stylized three-dimensional cartoon mobile game art teal teal magenta turquoise" },
  { id: "pocket-lab-pals", title: "Pocket Lab Pals", cat: "Characters & Lifestyle", land: false, dot: "#65BABD", hay: "pocket lab pals characters & lifestyle pet care doctor simulation time management kids game colorful clinic laboratory child dog friendly busy educational stylized three-dimensional cartoon character casual game art teal teal orange gold" },
  { id: "candy-river-quest", title: "Candy River Quest", cat: "Kids & Casual", land: false, dot: "#9A8562", hay: "candy river quest kids & casual match-three board game puzzle casual winding candy map castles mushrooms fantasy river sweet whimsical inviting stylized three-dimensional cartoon map mobile game art gold gold teal lime green crimson" },
  { id: "cactus-chomp-canyon", title: "Cactus Chomp Canyon", cat: "Adventure & Platformer", land: true, dot: "#E05047", hay: "cactus chomp canyon adventure & platformer platformer adventure kids game casual desert canyon cactus flying green creature platforms playful bold sunny cartoon two-dimensional colorful platformer art side-scroller red red orange teal green" },
  { id: "foxglove-meadow", title: "Foxglove Meadow", cat: "Adventure & Platformer", land: true, dot: "#8AC5CC", hay: "foxglove meadow adventure & platformer platformer cozy adventure kids game exploration autumn meadow foxes giant mushroom woodland peaceful whimsical warm painterly two-dimensional storybook art side-scroller teal teal yellow brown gold" },
  { id: "cubeface-carnival", title: "Cubeface Carnival", cat: "Adventure & Platformer", land: true, dot: "#37BCBE", hay: "cubeface carnival adventure & platformer platformer puzzle platformer kids game casual colorful block world cube creature panda floating platforms quirky cheerful bright cartoon two-dimensional colorful platformer art side-scroller teal teal red gold green" },
  { id: "block-balloon-bay", title: "Block Balloon Bay", cat: "Adventure & Platformer", land: true, dot: "#5EB2DA", hay: "block balloon bay adventure & platformer platformer puzzle casual adventure kids game floating block city balloons clouds platforms buoyant colorful energetic cartoon two-dimensional colorful platformer art side-scroller turquoise turquoise red teal silver" },
  { id: "rosy-ridge-run", title: "Rosy Ridge Run", cat: "Adventure & Platformer", land: true, dot: "#66BED3", hay: "rosy ridge run adventure & platformer platformer precision platformer minimalist adventure indie game pink cliffs small red character clouds distant city dreamy calm focused pixel art minimalist two-dimensional side-scroller teal teal orange magenta" },
  { id: "candybrick-canyon", title: "Candybrick Canyon", cat: "Adventure & Platformer", land: true, dot: "#51A8D9", hay: "candybrick canyon adventure & platformer platformer puzzle casual adventure kids game pastel block ruins floating cubes desert clouds playful airy vibrant painterly two-dimensional colorful platformer art side-scroller turquoise turquoise rose blue teal" },
  { id: "bunny-moon-bounce", title: "Bunny Moon Bounce", cat: "Adventure & Platformer", land: true, dot: "#3791DB", hay: "bunny moon bounce adventure & platformer platformer puzzle kids game casual pink cloudscape black bunny giant moon floating cubes dreamy cute surreal flat two-dimensional minimalist cartoon side-scroller turquoise turquoise pink rose" },
  { id: "blushstone-crossing", title: "Blushstone Crossing", cat: "Adventure & Platformer", land: true, dot: "#5CA6C5", hay: "blushstone crossing adventure & platformer platformer precision platformer adventure puzzle pink canyon ruins tiny character stone platforms pastel sky serene mysterious warm painterly two-dimensional stylized platformer art side-scroller turquoise turquoise crimson violet rose" },
  { id: "bloodmoon-hollow", title: "Bloodmoon Hollow", cat: "Adventure & Platformer", land: true, dot: "#102930", hay: "bloodmoon hollow adventure & platformer metroidvania platformer dark fantasy adventure gothic ruins red moon bridges fire ominous epic atmospheric pixel-inspired two-dimensional painterly dark fantasy art teal teal red magenta" },
  { id: "skybrick-ascent", title: "Skybrick Ascent", cat: "Adventure & Platformer", land: false, dot: "#51B2C3", hay: "skybrick ascent adventure & platformer vertical platformer endless jumper mobile arcade puzzle red brick tower clouds tiny character vertical level focused airy playful pixel art two-dimensional mobile game art teal teal red" },
  { id: "treetop-tinytown", title: "Treetop Tinytown", cat: "Adventure & Platformer", land: false, dot: "#57A99A", hay: "treetop tinytown adventure & platformer vertical platformer exploration puzzle adventure jungle towers treetop village clouds forest canopy lush mysterious adventurous painterly two-dimensional stylized platformer art vertical level teal teal green orange" },
  { id: "cloudberry-coast", title: "Cloudberry Coast", cat: "Adventure & Platformer", land: false, dot: "#4AB2E7", hay: "cloudberry coast adventure & platformer vertical platformer kids game casual adventure puzzle tropical floating islands ocean clouds green platforms sunny gentle inviting cartoon two-dimensional colorful platformer art vertical level turquoise turquoise brown teal" },
];
